version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    cpus: "0.5"
    mem_limit: 200m
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-fallback
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile
    env_file:
      - .env
    networks:
      - caddy-fallback
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/Caddyfile:/config/Caddyfile
      - ./logs:/var/log/caddy
      - ./static:/var/www/public
      - caddy-data:/data
    restart: unless-stopped

networks:
  caddy-fallback:
    external: true

volumes:
  caddy-data: {}